version: "3.8"
services:
  mongodb:
    image: 'mongo'
    # container_name: 'mongodb'
    # env_file:
    #   - ./env/mongo.env
    volumes:
      - data:/data/db
    ports:
      - 27018:27017
  backend:
    build: ./backend
      # context: ./backend
      # dockerfile: Dockerfile
    env_file:
      - ./env/backend.env
    volumes:
      - ./backend:/app
      - logs:/app/logs
      - /app/node_modules
    ports:
      - 80:80
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs:
